import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MyPlanProvider from "./context/MyPlanContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[#0f1115] text-white`}
    >
      <body className="min-h-full flex flex-col">
        <MyPlanProvider>
          <ToastContainer />
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </MyPlanProvider>
        </body>
    </html>
  );
}
